name: run-tests

on:
  push:
    branches: [main]
    paths:
      - '**.php'
      - 'phpunit.**'
      - 'composer.**'
      - 'tests/**'
  pull_request:
    branches: [main]
    paths:
      - '**.php'
      - 'phpunit.**'
      - 'composer.**'
      - 'tests/**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [8.2, 8.1]
        stability: [prefer-stable]

    name: P${{ matrix.php }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, libxml, mbstring, fileinfo, sockets, exif, gd, zip, iconv
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: List Installed Dependencies
        run: composer show -D

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Execute tests
        run: vendor/bin/pest --ci
